name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    name: Run checks and tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - name: Wordle Check and test
        run: |
          rustup component add rust-src --toolchain stable-x86_64-unknown-linux-gnu
          cd wordle
          cargo fmt --all --check
          cargo clippy --all-targets -- -D warnings -A unused-imports
          cargo b
          cargo t

      - name: Session Check and test
        run: |
          rustup component add rust-src --toolchain stable-x86_64-unknown-linux-gnu
          cd session
          cargo fmt --all --check
          cargo clippy --all-targets -- -D warnings -A unused-imports
          cargo b
          cargo t
